version: '3'
services:
  sprint-webserver:
    build: .
    image: sprint-webserver:test
    ports:
      - "8080:8080"
    environment:
    - HOST_PORT=8080
    - DB_HOST=mongodb
    - DB_PORT=27017
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - "mongodb"

  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
