"""Package for all services."""
from .deltakere_service import DeltakereService
from .foto_service import FotoService
from .innstillinger_service import InnstillingerService
from .kjoreplan_service import KjoreplanService
from .klasser_service import KlasserService
from .resultat_heat_service import ResultatHeatService
from .resultat_service import ResultatService
from .start_service import StartListeService
