name: Tests webserver
on:
  push

defaults:
  run:
    working-directory: webserver

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2020.8.22
    - run: pip install poetry==1.1.4
    - run: pip install nox-poetry==0.6.0
    - run: nox

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        job_name: tests
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
